In [2]:
import pandas as pd
music = pd.read_csv("charts.csv")

In [3]:
music.shape

(26173514, 9)

In [4]:
music[music['streams'] > 2000000]

,title,rank,date,artist,url,region,chart,trend,streams
3234,Starboy,1,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,Global,top200,SAME_POSITION,3135625.0
3235,Closer,2,2017-01-01,"The Chainsmokers, Halsey",https://open.spotify.com/track/7BKLCZ1jbUBVqRi...,Global,top200,SAME_POSITION,3015525.0
3236,Let Me Love You,3,2017-01-01,"DJ Snake, Justin Bieber",https://open.spotify.com/track/4pdPtRcBmOSQDlJ...,Global,top200,MOVE_UP,2545384.0
3237,Rockabye (feat. Sean Paul & Anne-Marie),4,2017-01-01,Clean Bandit,https://open.spotify.com/track/5knuzwU65gJK7IF...,Global,top200,MOVE_DOWN,2356604.0
3238,One Dance,5,2017-01-01,"Drake, WizKid, Kyla",https://open.spotify.com/track/1xznGGDReH1oQq0...,Global,top200,SAME_POSITION,2259887.0
...,...,...,...,...,...,...,...,...,...
25251443,Stir Fry,15,2018-01-31,Migos,https://open.spotify.com/track/2UVbBKQOdFAekPT...,Global,top200,SAME_POSITION,2224809.0
25251444,Sick Boy,16,2018-01-31,The Chainsmokers,https://open.spotify.com/track/7jqDzXJS0K0Re8u...,Global,top200,SAME_POSITION,2157006.0
25251445,"Let Me Go (with Alesso, Florida Georgia Line &...",17,2018-01-31,Hailee Steinfeld,https://open.spotify.com/track/5AEtlRudpgdT5Ft...,Global,top200,SAME_POSITION,2054277.0
25251446,I Fall Apart,18,2018-01-31,Post Malone,https://open.spotify.com/track/75ZvA4QfFiZvzhj...,Global,top200,SAME_POSITION,2034143.0
25275673,God's Plan,1,2018-01-31,Drake,https://open.spotify.com/track/2XW4DbS6NddZxRP...,United States,top200,SAME_POSITION,3805533.0

In [5]:
music.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26173514 entries, 0 to 26173513
Data columns (total 9 columns):
 #   Column   Dtype
---  ------   -----
 0   title    object
 1   rank     int64
 2   date     object
 3   artist   object
 4   url      object
 5   region   object
 6   chart    object
 7   trend    object
 8   streams  float64
dtypes: float64(1), int64(1), object(7)
memory usage: 1.8+ GB

In [12]:
music.groupby('chart')['title'].value_counts()

chart    title
top200   Shape of You                   65262
         Believer                       58310
         Perfect                        52732
         Someone You Loved              50975
         Happier                        48362
                                        ...
viral50  점퍼 챙겨 나와 Always missing you        1
         젖어'S (Wet)                         1
         피 땀 눈물                             1
         환상통 Only One You Need              1
         ﻿Lay Down Your Blade               1
Name: count, Length: 210606, dtype: int64

In [8]:
music[music['title'] == 'Starboy']

,title,rank,date,artist,url,region,chart,trend,streams
28,Starboy,29,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,Argentina,top200,SAME_POSITION,65518.0
201,Starboy,1,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,Australia,top200,MOVE_UP,107350.0
408,Starboy,7,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,Austria,top200,MOVE_UP,9165.0
605,Starboy,3,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,Belgium,top200,MOVE_UP,17374.0
819,Starboy,17,2017-01-01,"The Weeknd, Daft Punk",https://open.spotify.com/track/5aAx2yezTd8zXrk...,Bolivia,top200,MOVE_DOWN,2480.0
...,...,...,...,...,...,...,...,...,...
25606434,Starboy,37,2021-02-11,"The Weeknd, Daft Punk",https://open.spotify.com/track/7MXVkk9YMctZqd1...,South Korea,viral50,MOVE_DOWN,NaN
25646367,Starboy,31,2021-02-12,"The Weeknd, Daft Punk",https://open.spotify.com/track/7MXVkk9YMctZqd1...,South Korea,viral50,MOVE_UP,NaN
25666554,Starboy,32,2021-02-13,"The Weeknd, Daft Punk",https://open.spotify.com/track/7MXVkk9YMctZqd1...,South Korea,viral50,MOVE_DOWN,NaN
25710113,Starboy,33,2021-02-14,"The Weeknd, Daft Punk",https://open.spotify.com/track/7MXVkk9YMctZqd1...,South Korea,viral50,MOVE_DOWN,NaN
26017226,Starboy,37,2021-02-28,"The Weeknd, Daft Punk",https://open.spotify.com/track/7MXVkk9YMctZqd1...,South Korea,viral50,NEW_ENTRY,NaN

In [ ]:
music.groupby('title').value_counts()

In [13]:
music.head()

,title,rank,date,artist,url,region,chart,trend,streams
0,Chantaje (feat. Maluma),1,2017-01-01,Shakira,https://open.spotify.com/track/6mICuAdrwEjh6Y6...,Argentina,top200,SAME_POSITION,253019.0
1,Vente Pa' Ca (feat. Maluma),2,2017-01-01,Ricky Martin,https://open.spotify.com/track/7DM4BPaS7uofFul...,Argentina,top200,MOVE_UP,223988.0
2,Reggaetón Lento (Bailemos),3,2017-01-01,CNCO,https://open.spotify.com/track/3AEZUABDXNtecAO...,Argentina,top200,MOVE_DOWN,210943.0
3,Safari,4,2017-01-01,"J Balvin, Pharrell Williams, BIA, Sky",https://open.spotify.com/track/6rQSrBHf7HlZjtc...,Argentina,top200,SAME_POSITION,173865.0
4,Shaky Shaky,5,2017-01-01,Daddy Yankee,https://open.spotify.com/track/58IL315gMSTD37D...,Argentina,top200,MOVE_UP,153956.0

In [14]:
music.tail()

,title,rank,date,artist,url,region,chart,trend,streams
26173509,BYE,46,2021-07-31,Jaden,https://open.spotify.com/track/3OUyyDN7EZrL7i0...,Vietnam,viral50,MOVE_UP,NaN
26173510,Pillars,47,2021-07-31,My Anh,https://open.spotify.com/track/6eky30oFiQbHUAT...,Vietnam,viral50,NEW_ENTRY,NaN
26173511,Gái Độc Thân,48,2021-07-31,Tlinh,https://open.spotify.com/track/2klsSb2iTfgDh95...,Vietnam,viral50,MOVE_DOWN,NaN
26173512,Renegade (feat. Taylor Swift),49,2021-07-31,Big Red Machine,https://open.spotify.com/track/1aU1wpYBSpP0M6I...,Vietnam,viral50,MOVE_DOWN,NaN
26173513,Letter to Jarad,50,2021-07-31,"LRN Slime, Shiloh Dynasty",https://open.spotify.com/track/508QhA2SncMbh5C...,Vietnam,viral50,MOVE_DOWN,NaN

In [15]:
music.isnull().sum()

title           11
rank             0
date             0
artist          18
url              0
region           0
chart            0
trend            0
streams    5851610
dtype: int64